url: "https://xcodebuildsettings.com"
title: Xcode Build Settings
description: >-
  A convenient reference of available build settings for Xcode projects.
email: mattt@nshipster.com
baseurl: ""
twitter_username: NSHipster
github_username: NSHipster

markdown: kramdown

include: [".well-known"]

exclude:
  - README*
  - LICENSE*
  - Gemfile*
  - Procfile
  - Rakefile
  - rakelib/
  - netlify.toml
  - _redirects
  - _functions/
  - vendor/
  - node_modules/

assets:
  source_maps: true
  compression: true
  defaults:
    js: { integrity: true }
    css: { integrity: true }
    img: { integrity: true }

jekyll_tidy:
  ignore_env: development
  compress_html: true
