Core Build System:
  - CoreBuildSystem
  - NativeBuildSystem
  - CodeSign
  - LinkExecutables
  - StripSymbols
  - CreateStaticLibrary
  - ProductPackagingUtility
  - EmbeddedBinaryValidationUtility
  - SourceVersioning
  - JamBuildSystem
  - TextBasedAPITool
  - xcmpCompileBuildSettings

Swift:
  - SwiftBuildSettings
  - SwiftCompiler
  - Swiftstdlibtool

Clang:
  - Clang
  - CPreprocessor
  - ASTBuilder
  - Shared
  - Device

Metal & OpenCL:
  - MetalCompiler
  - MetalLinker
  - OpenCL

Interface Builder:
  - XIBCompiler
  - NIBPostprocessor
  - StoryboardCompiler
  - StoryboardLinker
  - StoryboardPostprocessor

Assets & Resources:
  - AssetCatalogCompiler
  - RealityComposerProjectCompiler
  - ARKitSkyboxCompiler
  - USDZCompiler
  - CopyPlistFile
  - CopyStringsFile
  - CopyTiffFile
  - CompressPNGFiles
  - SiriIntentDefinitionCompiler
  - SceneKitShaderCompiler
  - SceneKitDocumentProcessor
  - SpriteKitTextureAtlasGenerator

Core Data:
  - DataModelCompilerMOMC
  - CoreDataMappingModelCompilerMAPC

Miscellaneous:
  - MacCatalyst
  - Simulator
  - XPCService
  - CoreMLModelCompiler
  - InstrumentsPackageBuilder
  - IOKitInterfaceGenerator
  - OSACompiler
  - DTrace
  - MiG
  - Nasm
  - Rez
  - Lex
  - Yacc
