name: CI/CD

env:
  DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer

on:
  schedule:
    - cron: 0 0 * * 0
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Dependencies
        id: bundler-cache
        uses: actions/cache@v1
        with:
          path: /vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Install Dependencies
        if: steps.bundler-cache.outputs.cache-hit != 'true'
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Generate Data Sources
        run: bundle exec rake data

      - name: Build Site
        run: JEKYLL_ENV=production bundle exec jekyll build

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Site
          path: _site

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: Site

      - name: Sync Site Contents
        run: |
          rsync -avzr --delete --exclude='.git/' --exclude='Site' Site/ .
          rm -rf Site/

      - name: Commit & Push Changes
        run: |
          git config --global user.email "bot@xcodebuildsettings.com"
          git config --global user.name "CI Bot"
          git add .
          git commit -a -m "Update site"
          git push origin gh-pages
